from . import academic_year
from . import grade_level
from . import subject
from . import school_class
from . import teacher
from . import parent
from . import student
from . import conduct
from . import admission
from . import attendance
from . import exam
from . import timetable
from . import fee
from . import library
from . import transport
from . import notice
from . import dashboard
